name: 'OpenWrt ImageBuilder'
description: 'Build OpenWrt custom images using ImageBuilder'
inputs:
  openwrt-device: 
    description: 'OpenWrt device ID'
    required: true
    default: 'bcm27xx-bcm2711'
  openwrt-version:
    description: 'OpenWrt version'
    required: true
    default: 'master'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - run: mkdir bin && ls -la . && chmod 555 bin
      shell: bash
    - run: docker run --rm -v "$(pwd)"/bin/:/home/build/openwrt/bin:rw openwrtorg/imagebuilder:${{ inputs.openwrt-device }}-${{ inputs.openwrt-version }} make image
      shell: bash
    - run: find .
      shell: bash
