# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
  
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
       
      - uses: izer-xyz/openwrt-imagebuilder-action@main
        with:
          profile: armvirt-32
          openwrt-version: 22.03.2
          packages: -firewall4 -ca-bundle -dnsmasq -dropbear -e2fsprogs -fstools -kmod-nft-offload -libustream-wolfssl -logd -mkf2fs mtd netifd -nftables odhcp6c -odhcpd-ipv6only -opkg -ppp -ppp-mod-pppoe procd procd-seccomp procd-ujail uci uclient-fetch urandom-seed urngd
          files: test/files
          disabled-services: dhcp
          extra-image-name: useless
          
      - run: |
         sudo chmod -R a+rw ./bin
         ls -la $(pwd)/bin/targets/armvirt/32
         gzip -d ./bin/targets/armvirt/32/openwrt-22.03.2-useless-armvirt-32-rootfs.cpio.gz || true
         docker run --rm \
           -v $(pwd)/bin/targets/armvirt/32:/openwrt \
           tianon/qemu \
             qemu-system-arm \
               -M virt \
               -kernel /openwrt/openwrt-22.03.2-useless-armvirt-32-zImage \
               -initrd /openwrt/openwrt-22.03.2-useless-armvirt-32-rootfs.cpio \
               -no-reboot -nographic
         
      - uses: actions/upload-artifact@v3
        with:
          name: firmwares
          path: bin/targets/*/*/*
