# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - run: sudo chmod -R +rw /var/lib/docker/image && sudo ls -la /var/lib/docker/image
      
      - uses: actions/cache@v3
        with: 
          key: 22.03.2
          path: |
            /var/lib/docker/image
    
      - uses: izer-xyz/openwrt-imagebuilder-action@main
        with:
          openwrt-version: 22.03.2
          packages: busybox -ppp -firewall4 -base-files -bcm27xx-gpu-fw -ca-bundle -cypress-firmware-43455-sdio -cypress-nvram-43455-sdio-rpi-4b -dnsmasq -dropbear -e2fsprogs -fstools -iwinfo -kernel -kmod-brcmfmac -kmod-fs-vfat -kmod-nft-offload -kmod-nls-cp437 -kmod-nls-iso8859-1 -kmod-sound-arm-bcm2835 -kmod-sound-core -kmod-usb-hid -kmod-usb-net-lan78xx -libc -libgcc  -libustream-wolfssl -logd -mkf2fs -mtd -netifd -nftables -odhcp6c -odhcpd-ipv6only -opkg -partx-utils -ppp-mod-pppoe -procd -procd-seccomp -procd-ujail -uci -uclient-fetch -urandom-seed -wpad-basic-wolfssl
          files: test/files
          disabled-services: dhcp
          
      
