# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
  
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
       
      - uses: izer-xyz/openwrt-imagebuilder-action@main
        with:
          profile: x86-64
          openwrt-version: 22.03.2
          packages: busybox -ppp -firewall4 -base-files -bcm27xx-gpu-fw -ca-bundle -cypress-firmware-43455-sdio -cypress-nvram-43455-sdio-rpi-4b -dnsmasq -dropbear -e2fsprogs -fstools -iwinfo -kernel -kmod-brcmfmac -kmod-fs-vfat -kmod-nft-offload -kmod-nls-cp437 -kmod-nls-iso8859-1 -kmod-sound-arm-bcm2835 -kmod-sound-core -kmod-usb-hid -kmod-usb-net-lan78xx -libc -libgcc  -libustream-wolfssl -logd -mkf2fs -mtd -netifd -nftables -odhcp6c -odhcpd-ipv6only -opkg -partx-utils -ppp-mod-pppoe -procd -procd-seccomp -procd-ujail -uci -uclient-fetch -urandom-seed -wpad-basic-wolfssl
          files: test/files
          disabled-services: dhcp
          extra-image-name: useless
          
      - run: |
         sudo gzip -d ./bin/targets/x86/64/openwrt-22.03.2-useless-x86-64-generic-squashfs-combined.img.gz
         docker run --rm -it \
           -e QEMU_NO_SERIAL=1 \
           -e QEMU_HDA=/rootfs.img \
           -v $(pwd)/bin/target/x86/64/openwrt-22.03.2-useless-x86-64-generic-squashfs-combined.img:/rootfs.img \
           tianon/qemu \
             start-qemu -nographic
         
      - uses: actions/upload-artifact@v3
        with:
          name: firmwares
          path: bin/targets/*/*/*
